---
title: "README"
format: gfm
editor: visual
---

## This repository is for analysis examples, scripts, and tools for genomics analyses in the Troutman lab.

-   [Processing RNA-seq data](Vignettes/Processing%20RNA-seq%20data.md)
-   [Introduction to RNA-seq analysis](Vignettes/Introduction-RNASeqAnalysis.md)
-   [Making a basic bar chart with ggplot2](Vignettes/Bar-Charts.md)
-   [Looping over bar charts with purrr](Vignettes/Nested-Bar-Charts.md)
-   [Exporting gene lists](Vignettes/Exporting-Gene-Lists.md)
-   [Merging RNA-seq TPM data with DeSeq2 differential expression data](Vignettes/Integrating-RNASeq-ExpressionTPM-with-DeSeq2.md)

#### See [Code](Code/) for example scripts and tools.

#### Just beginning? Here's some basics:

-   [Introduction to using linux through the command line](https://www.google.com/url?q=https%3A%2F%2Flinuxize.com%2Fpost%2Fbasic-linux-commands%2F&sa=D&sntz=1&usg=AOvVaw0ZJqXF8wmUJCKIjz-knmNo)
-   [R and RStudio for beginners](https://www.google.com/url?q=https%3A%2F%2Feducation.rstudio.com%2Flearn%2Fbeginner%2F&sa=D&sntz=1&usg=AOvVaw08rdWXjb4wuXkqngeyR6r1)
-   [CCHMC Biomedical Informatics Cluster Computing](https://bmi.cchmc.org/resources/clusters/computational-cluster)

#### Commonly used software:

-   [SciDAP](https://scidap.com) - User friendly scientific data analysis platform that is freely accessible by members of the Division of Allergy and Immunology at CCHMC. Developed by [Artem Barksi](https://www.google.com/url?q=https%3A%2F%2Fwww.cincinnatichildrens.org%2Fresearch%2Fdivisions%2Fa%2Fallergy-immunology%2Flabs%2Fbarski&sa=D&sntz=1&usg=AOvVaw0FXvk5eS0ty1_Y_ViQIqyI) and Andrey Kartashov as part of [Datirium](https://www.google.com/url?q=https%3A%2F%2Fdatirium.com%2Flanding&sa=D&sntz=1&usg=AOvVaw2VrIG-Wzp9Qd9BT_4AIEvI).
-   [HOMER](http://homer.ucsd.edu/homer/) - Software for next generation sequencing analysis and motif discovery. Developed in Christopher Glass's lab at UC San Diego by Christopher Benner. Actively maintained in [Christopher Benner's lab](http://www.google.com/url?q=http%3A%2F%2Fhomer.ucsd.edu%2FBennerLab%2F&sa=D&sntz=1&usg=AOvVaw1EkyXjJPdqFWo3AsiSI2Mn) at UC San Diego.
-   [A.C.RSuite](https://github.com/z5ouyang/A.C.Rsuite) - Command line tool suite to generate preliminary results and images using HOMER and R. Developed in Christopher Glass's lab by Ouyang Zhang.
-   [MMARGE](https://github.com/vlink/marge) - Software enabling analysis of genetic variation with HOMER. Developed in Christopher Glass's lab by Verena Link.
-   [Seurat](https://satijalab.org/seurat/) - A robust and widely used analysis package for scRNA-seq data. Developed and maintained in [Rahul Satija's lab](https://www.google.com/url?q=https%3A%2F%2Fsatijalab.org&sa=D&sntz=1&usg=AOvVaw0xgBvL1FSt-eEGIA71KPEd) at NYU. "Seurat is an R package designed for QC, analysis, and exploration of single-cell RNA-seq data. Seurat aims to enable users to identify and interpret sources of heterogeneity from single-cell transcriptomic measurements, and to integrate diverse types of single-cell data."
-   [DeSeq2](https://scidap.com)
